[package]
name = "zktls-att-verification"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
aes-gcm = "0.10"
aead = "0.4"
aes = "0.8"
serde = {version = "1.0", features=["derive"]}
serde_json = "1.0"
hex= "0.4"
anyhow = "1.0"

k256 = "0.13.4"
sha2 = "0.9"
structopt = "0.3"

[patch.crates-io]
ecdsa-core = { git = "https://github.com/sp1-patches/signatures", package = "ecdsa", tag="ecdsa-v0.16.9-patch-v3.3.0" }

[dev-dependencies]
criterion = "0.5"

[profile.bench]
opt-level = 3
debug = false
split-debuginfo = "unpacked"
lto = true

[[bench]]
name = "benchmark"
harness = false

[[bin]]
name = "keygen_k256"
path = "bin/keygen_k256.rs"

[[bin]]
name = "sign_k256"
path = "bin/sign_k256.rs"

[[example]]
name = "verification_example"
path = "examples/verification_example.rs"

