[package]
name = "aes_verification"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
aes-gcm = "0.10"
aead = "0.4"
aes = "0.8"
serde = {version = "1.0", features=["derive"]}
serde_json = "1.0"
hex= "0.4"
